### ISSUE TITLE
api_call complains about unexpected keyword argument

### ISSUE THREAD

**Issue by alpinweis** [errbotio/err-backend-slackv3#54]
I'm using the `SlackV3` backend (latest `main` branch), migrating from the old `slack` backend. All calls to `self._bot.api_call` seem to fail complaining about unexpected keyword arguments.

Examples:
```
self._bot.api_call("users.list", data={"limit": 1000})
# ERROR: api_call() got an unexpected keyword argument 'limit'

self._bot.api_call("conversation.create", data={"name": "test"})
# ERROR: api_call() got an unexpected keyword argument 'name'
```

**Comment by nzlosh** [comment]
Thank you for taking the time to open this issue.

I've taken a look at the errbot code and this is my understanding:  The underlying slack webclient signature has changed between [v1](https://github.com/slackapi/python-slack-sdk/blob/c3deb70849fd99290b246df29ab8f1c6a68f172f/slackclient/client.py#L146) and [v3](https://github.com/slackapi/python-slack-sdk/blob/dac21c372626892419e12a096db91bdb05498234/slack_sdk/web/base_client.py#L71).  Errbot takes a `data` dictionary and passes the contents [as-is](https://github.com/errbotio/err-backend-slackv3/blob/d9b2cfee38131479bf5c11afd7c7c9210ec45411/slackv3.py#L120) to the slack module using [dictionary unpacking](https://www.python.org/dev/peps/pep-0448/).  `data` is intentionally undefined so that it can be adapted by the calling code to fit any use cases.

In your above example, the v1 code consumed the unpacked dictionary through the use of the `**kwargs` argument.

The v1 signature looks like this:
```
def api_call(self, method, timeout=None, **kwargs)
```

To use the SlackSDK v3 `api_call` method, the `data` dictionary will need to be adapted.  It looks like `data` dictionary will need to have a `data` or `json` key/value that would be passed to the API call.  I'd recommend looking at the [official Slack API documentation](https://api.slack.com/methods) to know the required parameters for each call.

The SlackSDK v3 signature looks like this:
```
def api_call(self, api_method: str, *, http_verb: str = "POST", files: dict = None, data: Union[dict] = None, params: dict = None, json: dict = None,  headers: dict = None, auth: dict = None)
```

I've not tested the below code but I think the example could be made to work with the following:

```
self._bot.api_call("conversation.create", data={"data": {"name": "test"}})
```

Unfortunately, I don't see a sane default to insulate v1 calling code so that it works directly with the v3 slacksdk client.  I hope that helps.  Let me know if this resolves your issue in an acceptable way and I'll create another issue to improve the documentation around how to use `api_call`.

**Comment by alpinweis** [comment]
As a quick workaround I went with calling `self._bot.slack_web` instead of `self._bot.api_call`.e.g.
```
self._bot.slack_web.conversations_create(name="test").
```
instead of 
```
self._bot.api_call("conversations.create", data=dict(name="test"))
```

**Comment by nzlosh** [comment]
`slack_web` is not intended to be accessed directly, so there's no guarantee to its stability.  That said, calling down into the Slack module through errbot's thin `api_call` wrapper didn't provide much protection from the underlying module changes either, so you've probably picked the least disruptive option.  I'll go ahead and close this issue.
